//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmBle.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmBle.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault Mode.
        /// </summary>
        internal static string AlarmSettingsLabel_AssaultMode {
            get {
                return ResourceManager.GetString("AlarmSettingsLabel_AssaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Passkey.
        /// </summary>
        internal static string AlarmSettingsLabel_ChangePasskey {
            get {
                return ResourceManager.GetString("AlarmSettingsLabel_ChangePasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Sensor.
        /// </summary>
        internal static string AlarmSettingsLabel_MovementSensor {
            get {
                return ResourceManager.GetString("AlarmSettingsLabel_MovementSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence Mode.
        /// </summary>
        internal static string AlarmSettingsLabel_PresenceMode {
            get {
                return ResourceManager.GetString("AlarmSettingsLabel_PresenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensibilidade.
        /// </summary>
        internal static string AlarmSettingsLabel_Sensibility {
            get {
                return ResourceManager.GetString("AlarmSettingsLabel_Sensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        internal static string AppSettings_AppLanguage {
            get {
                return ResourceManager.GetString("AppSettings_AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use biometrics to enter in the app.
        /// </summary>
        internal static string AppSettings_Biometrics {
            get {
                return ResourceManager.GetString("AppSettings_Biometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me check if you are really you!.
        /// </summary>
        internal static string BiometricAuth_Reason {
            get {
                return ResourceManager.GetString("BiometricAuth_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put your finger here.
        /// </summary>
        internal static string BiometricAuth_Title {
            get {
                return ResourceManager.GetString("BiometricAuth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string BiometricCancelOptionText {
            get {
                return ResourceManager.GetString("BiometricCancelOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Passkey.
        /// </summary>
        internal static string ChangePasskeyButton_SavePasskey {
            get {
                return ResourceManager.GetString("ChangePasskeyButton_SavePasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Passkey.
        /// </summary>
        internal static string ChangePasskeyLabel_CurrentPasskey {
            get {
                return ResourceManager.GetString("ChangePasskeyLabel_CurrentPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passkey.
        /// </summary>
        internal static string ChangePasskeyLabel_NewPasskey {
            get {
                return ResourceManager.GetString("ChangePasskeyLabel_NewPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not allowed here! Bye!.
        /// </summary>
        internal static string DialogAuth_AccessDenied_Message {
            get {
                return ResourceManager.GetString("DialogAuth_AccessDenied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string DialogAuth_AccessDenied_Title {
            get {
                return ResourceManager.GetString("DialogAuth_AccessDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AlarmBLE.
        /// </summary>
        internal static string DialogAuth_AccessGranted_Message {
            get {
                return ResourceManager.GetString("DialogAuth_AccessGranted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Granted.
        /// </summary>
        internal static string DialogAuth_AccessGranted_Title {
            get {
                return ResourceManager.GetString("DialogAuth_AccessGranted_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogButtonText_No {
            get {
                return ResourceManager.GetString("DialogButtonText_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogButtonText_Yes {
            get {
                return ResourceManager.GetString("DialogButtonText_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to connect to remote device?.
        /// </summary>
        internal static string DialogConnection_Message {
            get {
                return ResourceManager.GetString("DialogConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string DialogConnection_Title {
            get {
                return ResourceManager.GetString("DialogConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English USA.
        /// </summary>
        internal static string DialogLanguage_OptionEnUS {
            get {
                return ResourceManager.GetString("DialogLanguage_OptionEnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português Brasil.
        /// </summary>
        internal static string DialogLanguage_OptionPtBR {
            get {
                return ResourceManager.GetString("DialogLanguage_OptionPtBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app language.
        /// </summary>
        internal static string DialogLanguage_Title {
            get {
                return ResourceManager.GetString("DialogLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DialogTheme_OptionDark {
            get {
                return ResourceManager.GetString("DialogTheme_OptionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string DialogTheme_OptionLight {
            get {
                return ResourceManager.GetString("DialogTheme_OptionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System (Default).
        /// </summary>
        internal static string DialogTheme_OptionSystem {
            get {
                return ResourceManager.GetString("DialogTheme_OptionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app theme.
        /// </summary>
        internal static string DialogTheme_Title {
            get {
                return ResourceManager.GetString("DialogTheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found.
        /// </summary>
        internal static string EmptyText_NoDevicesFound {
            get {
                return ResourceManager.GetString("EmptyText_NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No paired devices.
        /// </summary>
        internal static string EmptyText_NoPairedDevices {
            get {
                return ResourceManager.GetString("EmptyText_NoPairedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string LabelStatus_Active {
            get {
                return ResourceManager.GetString("LabelStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string LabelStatus_Inactive {
            get {
                return ResourceManager.GetString("LabelStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Alarm.
        /// </summary>
        internal static string LabelText_ActivateAlarm {
            get {
                return ResourceManager.GetString("LabelText_ActivateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Devices.
        /// </summary>
        internal static string LabelText_AvailableDevices {
            get {
                return ResourceManager.GetString("LabelText_AvailableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep.
        /// </summary>
        internal static string LabelText_Beep {
            get {
                return ResourceManager.GetString("LabelText_Beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink.
        /// </summary>
        internal static string LabelText_Blink {
            get {
                return ResourceManager.GetString("LabelText_Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Alarm.
        /// </summary>
        internal static string LabelText_DeactivateAlarm {
            get {
                return ResourceManager.GetString("LabelText_DeactivateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LabelText_Location {
            get {
                return ResourceManager.GetString("LabelText_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page development in progress!.
        /// </summary>
        internal static string LabelText_PageDevelopmentInProgress {
            get {
                return ResourceManager.GetString("LabelText_PageDevelopmentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Devices.
        /// </summary>
        internal static string LabelText_PairedDevices {
            get {
                return ResourceManager.GetString("LabelText_PairedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string LabelText_Undefined {
            get {
                return ResourceManager.GetString("LabelText_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        internal static string MenuItem_AddDevice {
            get {
                return ResourceManager.GetString("MenuItem_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuItem_Home {
            get {
                return ResourceManager.GetString("MenuItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow.
        /// </summary>
        internal static string NullValueText_Unknow {
            get {
                return ResourceManager.GetString("NullValueText_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Settings.
        /// </summary>
        internal static string TabName_AlarmSettings {
            get {
                return ResourceManager.GetString("TabName_AlarmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string TabName_AppSettings {
            get {
                return ResourceManager.GetString("TabName_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already active.
        /// </summary>
        internal static string ToastText_AlreadyActive {
            get {
                return ResourceManager.GetString("ToastText_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already inactive.
        /// </summary>
        internal static string ToastText_AlreadyInactive {
            get {
                return ResourceManager.GetString("ToastText_AlreadyInactive", resourceCulture);
            }
        }
    }
}
